# Generated by Django 6.0.2 on 2026-05-24 16:59

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_reviewrating_review'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='variation',
            constraint=models.UniqueConstraint(models.F('product'), models.F('variation_category'), django.db.models.functions.text.Lower('variation_value'), name='unique_product_variation_value_ci', violation_error_message='The selected variation has been chosen.'),
        ),
    ]
