# Generated by Django 6.0.2 on 2026-05-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
    ]
