# Generated by Django 6.0.2 on 2026-05-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_payment_currency_payment_payer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
