# Generated by Django 6.0.2 on 2026-05-18 02:37

from django.db import migrations, models


def mark_existing_paid_orders_stock_deducted(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(is_ordered=True).update(stock_deducted=True)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            mark_existing_paid_orders_stock_deducted,
            migrations.RunPython.noop,
        ),
    ]
